# Generated by Django 2.1.3 on 2019-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='version',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
