# Generated by Django 2.1.3 on 2018-12-27 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
